/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EmployeeForms;

import Models.Guest;
import Models.Staff;
import Services.DBFunctionsGuest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ClientForm extends javax.swing.JFrame {

    Staff staff;
    ArrayList<Guest> guestList = new ArrayList();
    DBFunctionsGuest dbFunctions = new DBFunctionsGuest();
    
    public ClientForm() {
        initComponents();
        loadGuestToTable();
    }
    
    public ClientForm(Staff staff){
        this.staff = staff;
        initComponents();
        loadGuestToTable();
    }

    public void loadGuestToTable(){
         dbFunctions.Connect();
         guestList = dbFunctions.getAllGuests();
         
         DefaultTableModel dtm = new DefaultTableModel();
        
            dtm.addColumn("ID");
            dtm.addColumn("Ime");
            dtm.addColumn("Prezime");
            dtm.addColumn("Email");
            dtm.addColumn("Telefon");
            
            Object Client[] = new Object[5];
            
            for(int i = 0; i<guestList.size(); i++){
                Client[0] = guestList.get(i).getID();
                Client[1] = guestList.get(i).getFirstName();
                Client[2] = guestList.get(i).getLastName();
                Client[3] = guestList.get(i).getEmail();
                Client[4] = guestList.get(i).getPhone();
                dtm.addRow(Client);
            }
            
            this.guests_TABLE.setModel(dtm);
    }
    
    public boolean provjeraPassworda(String password) {
        if (password.length() < 8) {
            JOptionPane.showMessageDialog(this, "Šifra mora da sadrži najmanje 8 karaktera.");
            return false;
        }

        boolean hasNumber = false;
        for (char c : password.toCharArray()) {
            if (Character.isDigit(c)) {
                hasNumber = true;
                break;
            }
        }

        if (!hasNumber) {
            JOptionPane.showMessageDialog(this, "Šifra mora da sadrži najmanje jedan broj.");
            return false;
        }

        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ime_TB = new javax.swing.JTextField();
        changePw_BT = new javax.swing.JButton();
        prezime_TB = new javax.swing.JTextField();
        email_TB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        guests_TABLE = new javax.swing.JTable();
        telefon_TB = new javax.swing.JTextField();
        dodaj_BT = new javax.swing.JButton();
        a = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        b = new javax.swing.JLabel();
        sifra_TB = new javax.swing.JPasswordField();
        c = new javax.swing.JLabel();
        potvrdiSifru_TB = new javax.swing.JPasswordField();
        s = new javax.swing.JLabel();
        update_BT = new javax.swing.JButton();
        j = new javax.swing.JLabel();
        clear_BT = new javax.swing.JButton();
        d = new javax.swing.JLabel();
        delete_BT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        changePw_BT.setText("Promjena sifre");
        changePw_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePw_BTActionPerformed(evt);
            }
        });

        guests_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        guests_TABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guests_TABLEMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(guests_TABLE);

        dodaj_BT.setText("Dodaj");
        dodaj_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodaj_BTActionPerformed(evt);
            }
        });

        a.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        a.setText("Ime");

        jButton1.setText("Nazad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        b.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        b.setText("Prezime");

        c.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        c.setText("Email");

        s.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s.setText("Sifra");

        update_BT.setText("Izmjeni");
        update_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_BTActionPerformed(evt);
            }
        });

        j.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        j.setText("Potvrdi sifru");

        clear_BT.setText("Ocisti");
        clear_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_BTActionPerformed(evt);
            }
        });

        d.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        d.setText("Telefon");

        delete_BT.setText("Obrisi");
        delete_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_BTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(telefon_TB, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ime_TB, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                            .addComponent(prezime_TB)
                                            .addComponent(email_TB)
                                            .addComponent(sifra_TB)
                                            .addComponent(potvrdiSifru_TB)))
                                    .addComponent(jButton1))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(delete_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dodaj_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(changePw_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clear_BT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(update_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a)
                            .addComponent(ime_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b)
                            .addComponent(prezime_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c)
                            .addComponent(email_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s)
                            .addComponent(sifra_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j)
                            .addComponent(potvrdiSifru_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(d)
                            .addComponent(telefon_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dodaj_BT)
                            .addComponent(update_BT)
                            .addComponent(delete_BT))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clear_BT)
                            .addComponent(changePw_BT)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePw_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePw_BTActionPerformed
//        new GuestPasswordChange().setVisible(true);
//        dispose();
    }//GEN-LAST:event_changePw_BTActionPerformed

    private void guests_TABLEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guests_TABLEMousePressed
        Guest selectedGuest = guestList.get(guests_TABLE.getSelectedRow());

        ime_TB.setText(selectedGuest.getFirstName());
        prezime_TB.setText(selectedGuest.getLastName());
        email_TB.setText(selectedGuest.getEmail());
        sifra_TB.setEnabled(false);
        sifra_TB.setText("");
        potvrdiSifru_TB.setEnabled(false);
        potvrdiSifru_TB.setText("");
        telefon_TB.setText(selectedGuest.getPhone());
    }//GEN-LAST:event_guests_TABLEMousePressed

    private void dodaj_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodaj_BTActionPerformed
        String ime = ime_TB.getText();
        String prezime = prezime_TB.getText();
        String email = email_TB.getText();
        String password = sifra_TB.getText();
        String confirmPassword = potvrdiSifru_TB.getText();
        String phone = telefon_TB.getText();
        double balance = 0;
        
        if (!ime.isEmpty() && !prezime.isEmpty() && !email.isEmpty() && !password.isEmpty() && !confirmPassword.isEmpty() && !phone.isEmpty()) {
            if (password.equals(confirmPassword)) {
                if (provjeraPassworda(password)) {
                    Guest guest = new Guest(ime, prezime, email, password, phone, balance);

                    dbFunctions.Connect();
        System.out.println("Minecraft");
                    if (dbFunctions.addGuest(guest)) {
                        JOptionPane.showMessageDialog(this, "Gost uspjesno dodat.");
                        loadGuestToTable();
                    } else {
                        JOptionPane.showMessageDialog(this, "Doslo je do greske.");
                    }
                }
            }
        }
    }//GEN-LAST:event_dodaj_BTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(staff.getIsAdmin() == 1){
           new AdminMenu(staff.getID()).setVisible(true);
           dispose(); 
        }else{
            new EmployeeForm(staff.getID()).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void update_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_BTActionPerformed
        int id = 0;
        Object idValue = guests_TABLE.getValueAt(guests_TABLE.getSelectedRow(), 0);
        if(idValue != null){
            id = (int) idValue;
        }

        dbFunctions.Connect();
        Guest guest = dbFunctions.getGuestById(id);

        String ime = ime_TB.getText();
        String prezime = prezime_TB.getText();
        String email = email_TB.getText();
        String phone = telefon_TB.getText();

        if(!ime.isEmpty() && !prezime.isEmpty() && !email.isEmpty() && !phone.isEmpty()){
            guest.setFirstName(ime);
            guest.setLastName(prezime);
            guest.setEmail(email);
            guest.setPhone(phone);

            dbFunctions.Connect();
            if(dbFunctions.updateGuest(guest)){
                JOptionPane.showMessageDialog(this, "Gost uspješno ažruriran.");
                loadGuestToTable();
            }else{
                JOptionPane.showMessageDialog(this, "Došlo je do greške.");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena.");
        }
    }//GEN-LAST:event_update_BTActionPerformed

    private void clear_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_BTActionPerformed
        ime_TB.setText("");
        prezime_TB.setText("");
        email_TB.setText("");
        sifra_TB.setEnabled(true);
        sifra_TB.setText("");
        potvrdiSifru_TB.setEnabled(true);
        potvrdiSifru_TB.setText("");
        telefon_TB.setText("");
    }//GEN-LAST:event_clear_BTActionPerformed

    private void delete_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_BTActionPerformed
        int id = 0;
        Object idValue = guests_TABLE.getValueAt(guests_TABLE.getSelectedRow(), 0);
        if(idValue != null){
            id = (int) idValue;
        }

        dbFunctions.Connect();
        if(dbFunctions.deleteGuest(id)){
            JOptionPane.showMessageDialog(this, "Gost uspješno obrisan.");
            loadGuestToTable();
        }else{
            JOptionPane.showMessageDialog(this, "Došlo je do greške.");
        }
    }//GEN-LAST:event_delete_BTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JButton changePw_BT;
    private javax.swing.JButton clear_BT;
    private javax.swing.JLabel d;
    private javax.swing.JButton delete_BT;
    private javax.swing.JButton dodaj_BT;
    private javax.swing.JTextField email_TB;
    private javax.swing.JTable guests_TABLE;
    private javax.swing.JTextField ime_TB;
    private javax.swing.JLabel j;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField potvrdiSifru_TB;
    private javax.swing.JTextField prezime_TB;
    private javax.swing.JLabel s;
    private javax.swing.JPasswordField sifra_TB;
    private javax.swing.JTextField telefon_TB;
    private javax.swing.JButton update_BT;
    // End of variables declaration//GEN-END:variables
}
