/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EmployeeForms;

import Models.Staff;
import Services.DBFunctionsStaff;
import Services.LoginService;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author petar
 */
public class EmployeePasswordForm extends javax.swing.JFrame {

    int staffId;
    DBFunctionsStaff dbFunctions = new DBFunctionsStaff();
    ArrayList<Staff> staffList = new ArrayList<>();
    LoginService ls = new LoginService();
    
    public EmployeePasswordForm() {
        initComponents();
    }
    
    public EmployeePasswordForm(int staffId){
        this.staffId = staffId;
        initComponents();
        loadStaffToTable();
    }
    
    public void loadStaffToTable(){
         dbFunctions.Connect();
         staffList = dbFunctions.GetAllStaff();
         
         DefaultTableModel dtm = new DefaultTableModel();
        
            dtm.addColumn("ID");
            dtm.addColumn("Ime");
            dtm.addColumn("Prezime");
            dtm.addColumn("Email");
            dtm.addColumn("Admin");
            
            Object Staff[] = new Object[5];
            
            for(int i = 0; i<staffList.size(); i++){
                Staff[0] = staffList.get(i).getID();
                Staff[1] = staffList.get(i).getFirstName();
                Staff[2] = staffList.get(i).getLastName();
                Staff[3] = staffList.get(i).getEmail();
                Staff[4] = staffList.get(i).getIsAdmin();
                dtm.addRow(Staff);
            }
            
            this.zaposleni_TABLE.setModel(dtm);
    }

    public boolean provjeraPassworda(String password) {
        if (password.length() < 8) {
            JOptionPane.showMessageDialog(this, "Šifra mora da sadrži najmanje 8 karaktera.");
            return false;
        }

        boolean hasNumber = false;
        for (char c : password.toCharArray()) {
            if (Character.isDigit(c)) {
                hasNumber = true;
                break;
            }
        }

        if (!hasNumber) {
            JOptionPane.showMessageDialog(this, "Šifra mora da sadrži najmanje jedan broj.");
            return false;
        }

        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        zaposleni_TABLE = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        oldPw_TF = new javax.swing.JPasswordField();
        newPw_TF = new javax.swing.JPasswordField();
        confirmNewPw_TF = new javax.swing.JPasswordField();
        resetPw_BT = new javax.swing.JButton();
        changePw_BT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        zaposleni_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(zaposleni_TABLE);

        jButton1.setText("Nazad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Izaberite korisnika za promjenu lozinke");

        jLabel2.setText("Stara šifra");

        jLabel3.setText("Nova šifra");

        jLabel4.setText("Potvrdite šifru");

        resetPw_BT.setText("Resetuj šifru");
        resetPw_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPw_BTActionPerformed(evt);
            }
        });

        changePw_BT.setText("Promijeni šifru");
        changePw_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePw_BTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(newPw_TF)
                                    .addComponent(oldPw_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(confirmNewPw_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resetPw_BT)
                                .addGap(35, 35, 35)
                                .addComponent(changePw_BT))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel1))))
                .addGap(18, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(oldPw_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(newPw_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(confirmNewPw_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resetPw_BT)
                            .addComponent(changePw_BT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new EmployeeForm(staffId).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resetPw_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPw_BTActionPerformed
        int id = 0;
        Object idValue = zaposleni_TABLE.getValueAt(zaposleni_TABLE.getSelectedRow(), 0);
        if(idValue != null){
            id = (int) idValue;
        }

        dbFunctions.Connect();
        Staff staff = dbFunctions.GetStaffMember(id);

        String newPw = newPw_TF.getText();
        String confirmNewPw = confirmNewPw_TF.getText();

        if(provjeraPassworda(newPw)){
            if(newPw.equals(confirmNewPw)){
                staff.setPassword(ls.hash256B64(newPw));
                if(dbFunctions.updateStaffMember(staff)){
                    JOptionPane.showMessageDialog(this, "Uspješno resetovana šifra!");
                }else{
                    JOptionPane.showMessageDialog(this, "Došlo je do greške.");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Nova šifra i se ne poklapa sa potvrdom nove šifre.");
            }
        }
    }//GEN-LAST:event_resetPw_BTActionPerformed

    private void changePw_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePw_BTActionPerformed
        int id = 0;
        Object idValue = zaposleni_TABLE.getValueAt(zaposleni_TABLE.getSelectedRow(), 0);
        if(idValue != null){
            id = (int) idValue;
        }

        dbFunctions.Connect();
        Staff staff = dbFunctions.GetStaffMember(id);

        String oldPw = oldPw_TF.getText();
        String newPw = newPw_TF.getText();
        String confirmNewPw = confirmNewPw_TF.getText();

        String hashedOldPw = ls.hash256B64(oldPw);
        if(provjeraPassworda(newPw)){
            if(hashedOldPw.equals(staff.getPassword())){
                if(newPw.equals(confirmNewPw)){
                    staff.setPassword(ls.hash256B64(newPw));
                    if(dbFunctions.updateStaffMember(staff)){
                        JOptionPane.showMessageDialog(this, "Šifra uspješno promijenjena!");
                    }else{
                        JOptionPane.showMessageDialog(this, "Došlo je do greške.");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Nova šifra i se ne poklapa sa potvrdom nove šifre.");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Unijeli ste pogrešnu staru šifru.");
            }
        }
    }//GEN-LAST:event_changePw_BTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeePasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeePasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeePasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeePasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeePasswordForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePw_BT;
    private javax.swing.JPasswordField confirmNewPw_TF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField newPw_TF;
    private javax.swing.JPasswordField oldPw_TF;
    private javax.swing.JButton resetPw_BT;
    private javax.swing.JTable zaposleni_TABLE;
    // End of variables declaration//GEN-END:variables
}
